export type Language = "zh" | "en";

const chineseCopy = {
  skip: "跳到主要内容",
  homeLabel: "返回首页",
  menuOpenLabel: "打开导航",
  menuCloseLabel: "关闭导航",
  navLabel: "主要导航",
  languageLabel: "语言选择",
  profileLabel: "个人信息",
  researchOverviewLabel: "研究概览",
  skillsLabel: "技术关注领域",
  stackAriaLabel: "技术栈",
  focusLabel: "关注方向",
  navAbout: "关于",
  navResearch: "研究",
  navOpenSource: "开源方向",
  navAwards: "荣誉",
  navContact: "联系",
  heroEyebrow: "研究 · 工程 · 开源",
  heroHello: "你好，我是",
  heroName: "陈天宇",
  heroPunctuation: "。",
  heroLede:
    "华南理工大学数据科学与大数据技术专业本科生，关注深度学习、大语言模型、RAG、AI Agent 与时序建模。",
  viewResearch: "查看研究",
  schoolLabel: "学校",
  schoolValue: "华南理工大学",
  disciplineLabel: "方向",
  disciplineValue: "AI × 时序学习",
  statusLabel: "状态",
  statusValue: "探索开源机会",
  profileIndex: "研究档案 / 01",
  visualKicker: "从信号中学习结构",
  aboutTitle: "把研究问题，落到可运行的代码里。",
  aboutP1:
    "我是华南理工大学未来技术学院数据科学与大数据技术专业本科生。我的兴趣位于机器学习研究与工程实践的交叉点：理解模型，也关心它如何被实现、验证与应用。",
  aboutP2:
    "我曾参与非侵入式负荷监测方向的深度学习研究，负责模型代码实现、实验运行、结果分析与可视化。目前正进一步探索大语言模型、检索增强生成与 Agent Memory。",
  skill1: "深度学习与 PyTorch",
  skill2: "时序建模与零样本学习",
  skill3: "大语言模型与 RAG",
  skill4: "AI Agent 与长期记忆",
  researchTitle: "在未标注家庭中，识别每一台电器的能耗。",
  paperType: "论文研究 · IEEE Transactions on Smart Grid",
  researchSummary:
    "面向目标家庭无设备级标签的真实场景，通过对比学习与多尺度双路径时序融合，实现具有跨域泛化能力的非侵入式负荷监测。",
  roleLabel: "我的参与",
  roleText: "模型代码实现、实验运行、结果分析与可视化。",
  doiLink: "查看 DOI / IEEE",
  problemLabel: "问题",
  problemText: "目标域只有总功率序列，没有单设备标签用于微调。",
  methodLabel: "方法",
  methodText: "对比学习、多尺度特征提取、残差功率解耦与双路径时序融合。",
  stackLabel: "技术",
  openSourceTitle: "把模型能力，连接到真实系统。",
  openSourceIntro: "腾讯开源人才计划关注方向：大模型应用、Agent 长期记忆与可靠的知识检索。",
  focus1: "关注大语言模型的能力边界、应用开发与工程优化。",
  focus2: "探索可检索、可演化的长期记忆如何支撑智能体决策。",
  focus3: "关注文档理解、检索增强生成与知识库应用体验。",
  awardsTitle: "持续验证分析、建模与协作能力。",
  award1Title: "美国大学生数学建模竞赛",
  award2Title: "华南理工大学数理大赛",
  award2Prize: "一等奖",
  award3Title: "大学生数学竞赛 · 广东赛区",
  award3Prize: "二等奖",
  award4Title: "华南理工大学“鼎甲杯”",
  award4Prize: "三等奖",
  contactTitle: "一起讨论研究、代码与开源。",
  contactText: "欢迎通过邮件、GitHub 或 ORCID 了解和联系我。",
  footerText: "以清晰的问题、可靠的实验与可运行的代码持续学习。",
  backTop: "返回顶部",
  title: "陈天宇｜研究与开源",
  description:
    "陈天宇，华南理工大学数据科学与大数据技术专业本科生，关注深度学习、大语言模型、RAG、AI Agent 与时序建模。",
  locale: "zh_CN",
} as const;

export type SiteCopy = { [Key in keyof typeof chineseCopy]: string };

const englishCopy: SiteCopy = {
  skip: "Skip to main content",
  homeLabel: "Back to home",
  menuOpenLabel: "Open navigation",
  menuCloseLabel: "Close navigation",
  navLabel: "Primary navigation",
  languageLabel: "Language selection",
  profileLabel: "Profile information",
  researchOverviewLabel: "Research overview",
  skillsLabel: "Technical interests",
  stackAriaLabel: "Technology stack",
  focusLabel: "Areas of interest",
  navAbout: "About",
  navResearch: "Research",
  navOpenSource: "Open Source",
  navAwards: "Recognition",
  navContact: "Contact",
  heroEyebrow: "Research · Engineering · Open Source",
  heroHello: "Hello, I’m",
  heroName: "Tianyu Chen",
  heroPunctuation: ".",
  heroLede:
    "An undergraduate in Data Science and Big Data Technology at South China University of Technology, focused on deep learning, large language models, RAG, AI agents, and time-series modeling.",
  viewResearch: "View research",
  schoolLabel: "University",
  schoolValue: "SCUT",
  disciplineLabel: "Focus",
  disciplineValue: "AI × Time Series",
  statusLabel: "Status",
  statusValue: "Exploring open source",
  profileIndex: "Research profile / 01",
  visualKicker: "Learning structure from signals",
  aboutTitle: "Turning research questions into working code.",
  aboutP1:
    "I am an undergraduate in Data Science and Big Data Technology at the School of Future Technology, South China University of Technology. My interests sit at the intersection of machine learning research and engineering: understanding models while caring about how they are implemented, evaluated, and applied.",
  aboutP2:
    "I have contributed to deep learning research on nonintrusive load monitoring, working on model implementation, experiment execution, result analysis, and visualization. I am now exploring large language models, retrieval-augmented generation, and agent memory.",
  skill1: "Deep Learning & PyTorch",
  skill2: "Time Series & Zero-Shot Learning",
  skill3: "Large Language Models & RAG",
  skill4: "AI Agents & Long-Term Memory",
  researchTitle: "Identifying appliance-level energy use in unlabeled homes.",
  paperType: "Research paper · IEEE Transactions on Smart Grid",
  researchSummary:
    "For realistic target homes without appliance-level labels, this research combines contrastive learning and multiscale dual-path temporal fusion to enable nonintrusive load monitoring with cross-domain generalization.",
  roleLabel: "My contribution",
  roleText: "Model implementation, experiment execution, result analysis, and visualization.",
  doiLink: "View DOI / IEEE",
  problemLabel: "Problem",
  problemText: "Only aggregate power sequences are available in the target domain, with no appliance-level labels for fine-tuning.",
  methodLabel: "Approach",
  methodText: "Contrastive learning, multiscale feature extraction, residual power decoupling, and dual-path temporal fusion.",
  stackLabel: "Stack",
  openSourceTitle: "Connecting model capabilities to real systems.",
  openSourceIntro:
    "Tencent Open Source Talent Plan interests: LLM applications, agent long-term memory, and reliable knowledge retrieval.",
  focus1: "Interested in the capability boundaries, application development, and engineering optimization of large language models.",
  focus2: "Exploring how retrievable, evolving long-term memory can support agent decision-making.",
  focus3: "Focused on document understanding, retrieval-augmented generation, and knowledge-base user experience.",
  awardsTitle: "Continuously testing analytical, modeling, and collaborative skills.",
  award1Title: "Mathematical Contest in Modeling",
  award2Title: "SCUT Mathematics & Physics Competition",
  award2Prize: "First Prize",
  award3Title: "Chinese Mathematics Competitions · Guangdong",
  award3Prize: "Second Prize",
  award4Title: "SCUT Dingjia Cup",
  award4Prize: "Third Prize",
  contactTitle: "Let’s discuss research, code, and open source.",
  contactText: "Reach me by email, GitHub, or ORCID.",
  footerText: "Keep learning through clear questions, reliable experiments, and working code.",
  backTop: "Back to top",
  title: "Tianyu Chen | Research & Open Source",
  description:
    "Tianyu Chen is a Data Science undergraduate at SCUT, focused on deep learning, LLMs, RAG, AI agents, and time-series modeling.",
  locale: "en_US",
};

export const siteCopy: Record<Language, SiteCopy> = {
  zh: chineseCopy,
  en: englishCopy,
};
